In [53]:
import numpy as np
def powered_matrix(vector,N):
        
    vector_list=[val for val in range(6)]
    vector=np.array(vector_list)
    powered_matrix=np.column_stack([vector**((N-1-i)) for i in range(N)])
    p=powered_matrix[1:]
    
    print(p)
  

    

In [54]:
powered_matrix(([1,2,3,5]),3)


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


In [55]:
powered_matrix(([2,4,6]),4)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
